# Generated by Django 4.2.2 on 2023-06-13 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ProductoCategoria',
        ),
    ]
